
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    hikari:
      pool-name: microservice-myblog-registry
      maximum-pool-size: 200
      minimum-idle: 20
      auto-commit: false
      connection-timeout: 60000
      idle-timeout: 60000
      initialization-fail-timeout: 1800000
      max-lifetime: 600000
      login-timeout: 30
      validation-timeout: 100000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: microservice-myblog-registry
server:
  port: 8899